# Uncomment this line to define a global platform for your project
# platform :ios, ‘8.0’

target 'SKUtilsSwift' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift2'

pod 'NVActivityIndicatorView'

pod 'RealmSwift'
pod 'ObjectMapper'

pod 'RxSwift'
pod 'RxCocoa'

pod 'Alamofire'

pod 'SWMessages'

pod 'Firebase/Core'
pod 'Firebase/Messaging'

  target 'SKUtilsSwiftTests' do
    inherit! :search_paths
    # Pods for testing
 pod 'RxBlocking'
 pod 'RxTests'
  end

end
