# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AuthFlow' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

#pod 'Hero'
#pod 'GoogleMaps'
pod 'Google/SignIn'
pod 'Google/Analytics'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'Alamofire'
pod 'NVActivityIndicatorView'
#pod 'AERecord'
#pod 'Groot'
pod 'SwiftyDrop'
  # Pods for GeoTouch

end
